// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "/home/dgarcia/DriverChrome/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1920, 1015));
    driver.findElement(By.cssSelector("#signup > .MuiButton-label")).click();
    driver.findElement(By.id("name")).sendKeys("Usuario1");
    driver.findElement(By.id("age")).click();
    driver.findElement(By.id("age")).sendKeys("20");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("Usuario1");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("usuario1");
    driver.findElement(By.cssSelector(".MuiButton-contained")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("Usuario1");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("usuario1");
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > #buttonPublicar > .MuiButton-label")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Prueba1");
    driver.findElement(By.name("content")).click();
    {
      WebElement element = driver.findElement(By.name("opinion"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("content")).sendKeys("Prueba1");
    driver.findElement(By.name("opinion")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2) > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2) > .MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    assertThat(driver.switchTo().alert().getText(), is("¡Publicado con éxito!"));
    driver.findElement(By.cssSelector("a .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) .MuiButton-label")).click();
    driver.findElement(By.cssSelector("a > .MuiButtonBase-root > .MuiButton-label")).click();
    driver.findElement(By.id("name")).sendKeys("Usuario2");
    driver.findElement(By.id("age")).click();
    driver.findElement(By.id("age")).sendKeys("20");
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("Usuario2");
    driver.findElement(By.id("password")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("password")).sendKeys("usuario2");
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("Usuario2");
    driver.findElement(By.id("password")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("password")).sendKeys("usuario2");
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiInputBase-input")).click();
    driver.findElement(By.cssSelector(".MuiInputBase-input")).sendKeys("Usuario1");
    assertThat(driver.switchTo().alert().getText(), is("¡Encontrado con éxito!"));
    driver.findElement(By.cssSelector("div:nth-child(2) > #buttonSuperFollow > .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    driver.findElement(By.cssSelector("a > #buttonPublicar > .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiInputBase-input")).click();
    driver.findElement(By.cssSelector(".MuiInputBase-input")).sendKeys("Usuario1");
    assertThat(driver.switchTo().alert().getText(), is("¡Encontrado con éxito!"));
    driver.findElement(By.cssSelector("div:nth-child(2) > #buttonSuperFollow > .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    driver.findElement(By.cssSelector("a .MuiButton-label")).click();
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) .MuiButton-label")).click();
  }
}
